### ISSUE TITLE
Status track of public node services

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#1]
This issue comes from [host a page for status monitoring and issue reporting](https://github.com/Magickbase/ckb-wallet-and-explorer/issues/12#issuecomment-1336378964), which requires an API for checking if godwoken node is running correctly.

The metric includes:
1. the timestamp of the tip block header should not fall behind real-world time too much
2. tip block numbers from the self-host node and the public node should be close

If the timestamp is behind real-world time too much, the node is not mining. There're two cases the node is not mining:
1. an exception is not handled correctly in a single node, so it is out of sync with peers, and its tip block number should fall behind peers;
2. all nodes stop working, so tip block numbers from peers are the same, but the timestamp of the tip block is outdated.

An API is required for a status page as https://betterstack.com/better-uptime, `success` should be returned if all services work well, while `error message` should be returned if one service is down.

-------

Now the public node service of ckb will be transferred to us, so the monitoring should be used with ckb nodes, too. `success` should be returned if the public node service is good, while `error` should be returned if the public node service is down.

**Comment by Keith-CY** [comment]
[CKB Guardian](https://cryptape.github.io/CkbGuardian/index.html) is more comprehensive, it tests every JSON RPC method of the node

Ref: https://github.com/cryptape/CkbGuardian

**Comment by Keith-CY** [comment]
How is it going?

**Comment by mdzh521** [comment]
ok, i got it. I just noticed this task. I will include him in the work content. sorry

**Comment by mdzh521** [comment]
I need to get some support about this monitoring.
1. First of all, I need back-end development students to help me get the block information on the relevant nodes.
2. Then the front-end students are required to make a display on the page for these block information and corresponding node information. Please ask @Keith-CY  to confirm what content needs to be displayed.

**Comment by Keith-CY** [comment]
> I need to get some support about this monitoring.
> 
> 1. First of all, I need back-end development students to help me get the block information on the relevant nodes.
> 2. Then the front-end students are required to make a display on the page for these block information and corresponding node information. Please ask @Keith-CY  to confirm what content needs to be displayed.

For point 2

> make a display on the page for these block information and corresponding node information

is not required, I was expecting an API to check health of nodes and if all nodes are working properly, the API returns `http status 200` and make `status page` green that day
![image](https://user-images.githubusercontent.com/7271329/210737719-d1055f58-b3d7-4499-93f3-908d46f0b61a.png)

If the nodes are not working correctly, the API returns `http status 500` with error message(`tip block info of public node and self-host node`) and make the `status page` red that day
![image](https://user-images.githubusercontent.com/7271329/210738071-35c3b097-fcc3-42b0-b46d-97561e56b9c7.png)

---

So all we're going to do is add an API to check health status of nodes, then monitor it by https://betterstack.com/better-uptime

Ref: https://betterstack.com/community/guides/monitoring/what-is-api-monitoring/#how-to-start-api-monitoring-in-2-minutes-with-better-uptime

**Comment by Keith-CY** [comment]
I'll add the service of checking nodes

**Comment by Keith-CY** [comment]
Status page preview: https://status.magickbase.com/
Health check API repo: https://github.com/Magickbase/public-service-status-checker

Health check API:
- ckb public node mainnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/mainnet
- ckb public node testnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/testnet

**Comment by mdzh521** [comment]
> Status page preview: https://magickbase.betteruptime.com/ Health check API repo: https://github.com/Magickbase/public-service-status-checker
> 
> Health check API:
> 
> * ckb public node mainnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/mainnet
> * ckb public node testnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/testnet

Which nodes are checked by these two health check interfaces? Is our ckb-node?

**Comment by Keith-CY** [comment]
> > Status page preview: [magickbase.betteruptime.com](https://magickbase.betteruptime.com/) Health check API repo: [Magickbase/public-service-status-checker](https://github.com/Magickbase/public-service-status-checker)
> > Health check API:
> > 
> > * ckb public node mainnet: [public-service-status-checker-magickbase.vercel.app/api/ckb/node/mainnet](https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/mainnet)
> > * ckb public node testnet: [public-service-status-checker-magickbase.vercel.app/api/ckb/node/testnet](https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/testnet)
> 
> Which nodes are checked by these two health check interfaces? Is our ckb-node?

CKB public nodes
- mainnet: https://mainnet.ckb.dev/rpc
- testnet: https://testnet.ckb.dev/rpc

**Comment by mdzh521** [comment]
ok，got it

**Comment by Keith-CY** [comment]
All public services are online
![image](https://user-images.githubusercontent.com/7271329/210790095-6b41f99c-8e29-43fc-8ead-090c4adbc2c1.png)

### CKB Node
- Mainnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/mainnet
- Testnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/node/testnet

### CKB Explorer
- Mainnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/explorer/mainnet
- Testnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/explorer/testnet

### Godwoken Explorer
- Mainnet: https://public-service-status-checker-magickbase.vercel.app/api/gw/explorer/mainnet
- Testnet: https://public-service-status-checker-magickbase.vercel.app/api/gw/explorer/testnet

### Faucet
- Testnet: https://public-service-status-checker-magickbase.vercel.app/api/ckb/faucet

**Comment by mdzh521** [comment]
ok, I will improve the alarm rules as soon as possible, thank you for your support

**Comment by mdzh521** [comment]
At present, the monitoring of our environment ckb-node node has been completed, and the monitoring of status and time stamp has been realized. The monitoring of ckb-explorer and related monitoring of faucet are being realized gradually.

**Comment by mdzh521** [comment]
Currently considering making a node display platform, covering the following elements: 
1. block height of all nodes (including ckb-node and godwoken deployed in our place) 
2. block height comparison alerts of all nodes in our place 
3. timestamp comparison alerts of all nodes in our place

This is all for now, we can continue to improve it later.

**Comment by mdzh521** [comment]
![Image](https://user-images.githubusercontent.com/40058127/233038455-8e06d3d4-b224-4fc4-9c7b-24f18ccda594.png)

**Comment by mdzh521** [comment]
This is a diagram showing all the nodes.

**Comment by Keith-CY** [comment]
> ![Image](https://user-images.githubusercontent.com/40058127/233038455-8e06d3d4-b224-4fc4-9c7b-24f18ccda594.png)

This is nice

**Comment by mdzh521** [comment]
Okay, so next I'll show the browser's here as well.

**Comment by mdzh521** [comment]
NODE node monitoring can be viewed directly through the browser at：https://grafana.layerview.io/d/tSqBCSE4k/ckb-node?orgId=1&refresh=5s
