### ISSUE TITLE
Upgrade godwoken to v1.12.0

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#17]
[Godwoken v1.12.0](https://github.com/godwokenrises/godwoken/blob/develop/CHANGELOG.md#v1120---2023-02-27)

I also noticed that the mainnet of gwscan was still at v1.7.3, should be updated simultaneously

**Comment by mdzh521** [comment]
Our mainnet godwoken has been upgraded to version 1.12.0, this is not showing the new version in sync because there is a problem with the godwoken callback interface and they say it is being fixed. https://github.com/godwokenrises/godwoken-internal/issues/1220
