### ISSUE TITLE
Migration function initialization bug fixed

### ISSUE THREAD

**Issue by mdzh521** [Magickbase/infra#3]
The Migration function is initialized, and it has been repaired in the staging environment, and there is no problem in viewing it.

**Comment by mdzh521** [comment]
The deployment method is deployed by initializing the container through kubernetest's init. The specific deployment method is shown in the figure.
![image](https://user-images.githubusercontent.com/40058127/212827378-750ab273-4441-4779-a218-b43b2f5b6d8d.png)

**Comment by mdzh521** [comment]
I want to confirm that the initialization of the migration only needs to be deployed in the POD of the syncer, or all three pods of the ckb explorer need to be deployed?

**Comment by Keith-CY** [comment]
@iamyates @ShiningRay

**Comment by mdzh521** [comment]
The bug has been fixed, and the testnet and mainnet environments have been updated synchronously.
