### ISSUE TITLE
Godwoken node and gwscan monitoring.

### ISSUE THREAD

**Issue by mdzh521** [Magickbase/infra#44]

**Comment by guomaoqiu** [comment]
Completed the Godwoken monitor function
![Image](https://github.com/Magickbase/infra/assets/9714859/d54767ab-15a1-4531-99a8-bb8a42f06298)

Grafana:
https://grafana.layerview.io/d/sif8wi9Vk/godwoken-node?orgId=1&refresh=5s

Prometheus:
![Image](https://github.com/Magickbase/infra/assets/9714859/5d64824c-3eb1-4c96-a268-2647bc50d83f)
