### ISSUE TITLE
Connect godwoken v0 explorer to the public node

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#48]
Now v0 is only for the inactive users to check data once they recall it. The node and explorer are not actively maintained.

Due to the tx-fee-free strategy, there are much more transactions on v0 than on v1

v0: 16,333,506
v1: 468,818

Data on v0 are huge but inactive, so we are going to connect the official public node instead of running our own.

The public node info can be found at https://github.com/godwokenrises/godwoken-info/tree/main/mainnet_v0

**Comment by guomaoqiu** [comment]
Done.
