### ISSUE TITLE
Upgrade godwoken v1 mainnet node from v1.13.0 to v1.14.0

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#51]
Ref: https://discord.com/channels/956765352514183188/1118184824801341480/1125611864508870706

Notice that v0 is frozen and v1 testnet is v1.14.0 already

**Comment by guomaoqiu** [comment]
Upgrade Completed 

1. Replace the GODWOKEN_JSON_RPC_URL of mainnet/gwscan-api with: https://v1.mainnet.godwoken.io/rpc (previously: http://gw-web3:8024/)
2. Modify the version number in the deployment file to: v1.14.0-smt-trie.
3. Check if the logs and monitoring data are normal.
4. Migration is completed and the RPC address will be switched back to the original http://gw-web3:8024/.


This upgrade will involve data migration, which has been defined in the dashboard of Kuboard. Simply follow the above steps.
<img width="1192" alt="image" src="https://github.com/Magickbase/infra/assets/9714859/2f981c80-0243-4aca-ab4f-cb25b45ff09d">
