### ISSUE TITLE
das-account-indexer standalone server new deployment

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#53]
New Das Mainnet Url: http://das.mainnet.layerview.io

Check Status Url:  `curl -X POST  http://das.mainnet.layerview.io/v1/server/info`

Currently in sync state.

**Comment by guomaoqiu** [comment]
At present, the synchronization has been completed and the service is running normally.

![Image](https://github.com/Magickbase/infra/assets/9714859/ddc95af9-f6ff-4f50-b12c-45ca34495fcd)

**Comment by guomaoqiu** [comment]
@zmcNotafraid 上周在独立服务器上面部署了最新版本的das-account-indexer服务，从k8s中抽离出来。目前独立服务正常运行中；需要确认一下：

1. Godwoken是否也用到了这个服务，如果有用到，是否可以复用？
2. CKB 这边如果切过去，能否安排个时间？
3. 目前仅部署了主网Mainnet，Testnet之前有部署痕迹，目是暂停状态，测试环境是否需要部署一套？

**Comment by zmcNotafraid** [comment]
> @zmcNotafraid 上周在独立服务器上面部署了最新版本的das-account-indexer服务，从k8s中抽离出来。目前独立服务正常运行中；需要确认一下：
> 
> 1. Godwoken是否也用到了这个服务，如果有用到，是否可以复用？
> 2. CKB 这边如果切过去，能否安排个时间？
> 3. 目前仅部署了主网Mainnet，Testnet之前有部署痕迹，目是暂停状态，测试环境是否需要部署一套？

1. 可以复用
2. 07/18 晚上21:00 是否可以？
3. testnet 不需要部署

**Comment by guomaoqiu** [comment]
> > @zmcNotafraid 上周在独立服务器上面部署了最新版本的das-account-indexer服务，从k8s中抽离出来。目前独立服务正常运行中；需要确认一下：
> > 
> > 1. Godwoken是否也用到了这个服务，如果有用到，是否可以复用？
> > 2. CKB 这边如果切过去，能否安排个时间？
> > 3. 目前仅部署了主网Mainnet，Testnet之前有部署痕迹，目是暂停状态，测试环境是否需要部署一套？
> 
> 1. 可以复用
> 2. testnet 不需要部署

没问题。
