### ISSUE TITLE
Mainnet ckb-explorer-sycenr service pod capacity split

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#54]
In order to ensure the high availability of service scheduling, the containers in this container are split into separate workloads, and the corresponding github action workflow jobs file needs to be adjusted, three pods:

- ckb-explorer-poolsyncer
- ckb-explorer-scheduler
- ckb-explorer-blocksyncer

Please help to change this. 
Deploy Env:  _**Maninet**_

**Comment by guomaoqiu** [comment]
@zmcNotafraid 目前主网、测试网 服务名称不统一、导致在github action中的部署编排执行报错，个人建议对各个环境中的服务名称进行一遍梳理后能够统一命名。

**Comment by zmcNotafraid** [comment]
> @zmcNotafraid 目前主网、测试网 服务名称不统一、导致在github action中的部署编排执行报错，个人建议对各个环境中的服务名称进行一遍梳理后能够统一命名。

可以的，有什么建议吗？ mainnet-ckb-explorer-poolsyncer/testnet-ckb-explorer-poolsyncer/staging-ckb-explorer-poolsyncer 这样行吗

**Comment by guomaoqiu** [comment]
嗯，这样可以；
尽量在一个Pod里面运行一个容器镜像，这样隔离性、稳定性也好点。

**Comment by guomaoqiu** [comment]
各个环境syncer服务拆分已完成。
