### ISSUE TITLE
Godwoken & CKB-Explorer, CKB-Node monitoring agent refactoring

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#56]
At present, explorer 、node monitoring indicators are relatively simple. When prometheus alarms, it is impossible to clearly understand which environment and what the current value is. It is necessary to modify the current monitoring agent to eliminate this vague notification information, and it is also more convenient to configure charts in grafana.

Refactoring items:

1. CKB:
- ckb explorer website status
- ckb explorer api status
- ckb explorer blockchain height
- monitor the environment in which the container is running
- ckb node blockchain height

2. Godwoken:
- godwoken explorer website status
- godwoken explorer api status
- godwoken explorer blockchain height
- monitor the environment in which the container is running
- godwoken  node blockchain height

3. CKB Faucet:
- faucet website status
- faucet api status

**Comment by guomaoqiu** [comment]
At present, the business service alarm configuration has been basically completed.

1. Critical level alarm through aiops alarm.
2. Other warning-level alarms are received by the devops administrator and dealt with accordingly.

The specific monitoring content can be seen in detail: [prometheus alert rules](http://prometheus.layerview.io/alerts?search=)

**Comment by guomaoqiu** [comment]
One page focuses on the state of each explorer:

https://full-monitor.layerview.io/

**Comment by Keith-CY** [comment]
> One page focuses on the state of each explorer:
> 
> [full-monitor.layerview.io](https://full-monitor.layerview.io/)

SSL and HSTS should be enabled

![image](https://github.com/Magickbase/infra/assets/7271329/69035a79-0f44-450a-a5d7-a3a5d25f5357)
![image](https://github.com/Magickbase/infra/assets/7271329/6ce70ff6-02de-4029-b4cf-481c2a520580)

**Comment by guomaoqiu** [comment]
ok, our domain name certificate is not unified (*.layerview.io), so we need to apply for a certificate for the domain name (https://full-monitor.layerview.io) separately.

**Comment by guomaoqiu** [comment]
> 

It has been processed, and I just found out that you can apply for an SSL certificate with one click for free through the pagoda fortress host.
![image](https://github.com/Magickbase/infra/assets/9714859/3a4866df-9285-4c45-b244-965821da5a71)

**Comment by guomaoqiu** [comment]
The external monitoring domain name https://full-monitor.magickbase.com/ has been configured. @Keith-CY
