### ISSUE TITLE
GitHub action deploys multiple containers of ckb-explorer synchronously, so all images cannot be updated synchronously.

### ISSUE THREAD

**Issue by mdzh521** [Magickbase/infra#6]
The problem with GitHub action's inability to synchronise mirror updates in real time is due to a versioning bug in kuboard, which required several debugging sessions to try to separate the mirror updates of three pods to see if it worked.

**Comment by mdzh521** [comment]
This problem is due to a synchronization bug in the kuboard software, for the time being there is no particularly good solution.

**Comment by mdzh521** [comment]
Mirror update method, ckb-explorer-api as an example.


![Image](https://github.com/Magickbase/infra/assets/40058127/70c222d3-65bb-4de9-b729-717134994118)

**Comment by guomaoqiu** [comment]
The above issues have been fixed
1. Service split
2.ci/cd bug fixes
