### ISSUE TITLE
Remove hosts of CKB Explorer Frontend once mainnet and testnet are migrated to vercel

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#66]
It's been a long time that Staging CKB Explorer has been deployed on vercel. The mainnet and testnet are expected to be migrated to vercel too because the Staging one works well.

After the migration, the host service can be declined on AWS.

I'll update the progress of migration in this issue.

**Comment by Keith-CY** [comment]
Testnet has been migrated to vercel

**Comment by guomaoqiu** [comment]
Okay, after the migration is completed, need to provide the front -end Web access URL. I will remove the stopped old domain name and service, and update the relevant monitoring configuration.

**Comment by Keith-CY** [comment]
Mainnet has been migrated

**Comment by Keith-CY** [comment]
> Okay, after the migration is completed, need to provide the front -end Web access URL. I will remove the stopped old domain name and service, and update the relevant monitoring configuration.

They are hosted on the same domains
- https://explorer.nervos.org
- https://pudge.explorer.nervos.org

So it's unnecessary to update monitoring.

**Comment by Keith-CY** [comment]
The thing we may do is to remove resources used to compile and host the pages

**Comment by guomaoqiu** [comment]
> 

Ok, the frontend service in k8s is suspended, I will delete it after 2 days.

**Comment by guomaoqiu** [comment]
Front-end service deployment has been completely removed from k8s.
