### ISSUE TITLE
Bump Godwoken Node to v1.15.0

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#69]
Godwoken Info: https://github.com/godwokenrises/godwoken-info/pull/101
Release: https://github.com/godwokenrises/godwoken/releases/tag/v1.15.0

**Comment by guomaoqiu** [comment]
The upgrade is completed without exception.

<img width="465" alt="image" src="https://github.com/Magickbase/infra/assets/9714859/9068ca53-17aa-44f5-9f4e-b65af749eb0c">
