### ISSUE TITLE
Enable API key for the public nodes

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#7]
Some partner teams require massive usage, and they've been listed in the whitelist. However, some of them work in WeWork, which provides dynamic IPs. So API keys are desirable.

It would be good to provide the API keys by 02/15. If it's too rush, we're going to provide another domain without rate limit for insider developers.

**Comment by mdzh521** [comment]
Is this for the public area testnet environment or the mainnet environment?

**Comment by Keith-CY** [comment]
> Is this for the public area testnet environment or the mainnet environment?

For both

**Comment by Keith-CY** [comment]
Is there a feasible plan to bypass the rate limit?

**Comment by mdzh521** [comment]
I think this needs to be made available to the rest of the team by setting up a separate domain in. Because now we have a gateway firewall that is not controlled by us, but is integrated inside the BaoTa software.

**Comment by mdzh521** [comment]
Or we can also adjust our protection policy appropriately, for example, before we were blacklisted for visiting the same url 120 times per minute. We can adjust to increase the frequency and number of visits appropriately.

**Comment by mdzh521** [comment]
New domains have been deployed and different interfaces are provided depending on the environment.
