### ISSUE TITLE
Bump CKB Node to v0.112.1

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#71]
CKB Node v0.112.1 has been released at https://github.com/nervosnetwork/ckb/releases/tag/v0.112.1 and the following node services can be updated

- Node of CKB Explorer Mainnet
- Node of CKB Explorer Testnet
- Node of Godwoken Explorer Mainnet(If it has its own independent ckb node)
- Node of Godwoken Explorer Testnet(If it has its own independent ckb node)
- Community CKB Node Mainnet
- Community CKB Node Testnet
- HOLDON: Node of Force Bridge because adaption is working in progress.

**Comment by guomaoqiu** [comment]
> CKB Node v0.112.1 has been released at https://github.com/nervosnetwork/ckb/releases/tag/v0.112.1 and the following node services can be updated
> 
> * Node of CKB Explorer Mainnet
> * Node of CKB Explorer Testnet
> * Node of Godwoken Explorer Mainnet(If it has its own independent ckb node)
> * Node of Godwoken Explorer Testnet(If it has its own independent ckb node)
> * Community CKB Node Mainnet
> * Community CKB Node Testnet
> * HOLDON: Node of Force Bridge because adaption is working in progress.

The above block nodes have been successfully upgraded to `v0.112.1`

**Comment by Keith-CY** [comment]
> > CKB Node v0.112.1 has been released at [nervosnetwork/ckb@`v0.112.1` (release)](https://github.com/nervosnetwork/ckb/releases/tag/v0.112.1) and the following node services can be updated
> > 
> > * Node of CKB Explorer Mainnet
> > * Node of CKB Explorer Testnet
> > * Node of Godwoken Explorer Mainnet(If it has its own independent ckb node)
> > * Node of Godwoken Explorer Testnet(If it has its own independent ckb node)
> > * Community CKB Node Mainnet
> > * Community CKB Node Testnet
> > * HOLDON: Node of Force Bridge because adaption is working in progress.
> 
> The above block nodes have been successfully upgraded to `v0.112.1`

v0.111.0 is still displayed in CKB Explorer Mainnet

**Comment by Keith-CY** [comment]
> > > CKB Node v0.112.1 has been released at [nervosnetwork/ckb@`v0.112.1` (release)](https://github.com/nervosnetwork/ckb/releases/tag/v0.112.1) and the following node services can be updated
> > > 
> > > * Node of CKB Explorer Mainnet
> > > * Node of CKB Explorer Testnet
> > > * Node of Godwoken Explorer Mainnet(If it has its own independent ckb node)
> > > * Node of Godwoken Explorer Testnet(If it has its own independent ckb node)
> > > * Community CKB Node Mainnet
> > > * Community CKB Node Testnet
> > > * HOLDON: Node of Force Bridge because adaption is working in progress.
> > 
> > 
> > The above block nodes have been successfully upgraded to `v0.112.1`
> 
> v0.111.0 is still displayed in CKB Explorer Mainnet

Updated
