### ISSUE TITLE
layerview.io domain name replacement, DNS update, and all configuration updates related to the domain name service.

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#75]
Due to historical issues with the domain name layerview.io, all involved domain names need to be replaced with the team’s magickbase.com domain name.

**Comment by guomaoqiu** [comment]
Currently, the layerview.io domain name has been replaced and needs to be updated by development colleagues:

1. The access domain name of the grafana page embedded in the status monitoring website is:  `https://grafana.magickbase.com` @Keith-CY 
![Image](https://github.com/Magickbase/infra/assets/9714859/ee7f37ff-41f1-40c0-8302-4ce8dbe48c12)

2. The Github Action `KUBOARD_API_URL` variables in all projects involving CI/CD on github are updated to: `https://kuboard.magickbase.com/kuboard-api/cluster/ckb/kind/CICDApi/ops/resource/updateImageTag` @rabbitz @zmcNotafraid 

Note: The variable names of each project may be different. Please replace them according to the specific variables in workflows. For example, in `ckb-explorer-api`, you only need to replace the domain name link： `https://kuboard.magickbase.com/kuboard-api`
![Image](https://github.com/Magickbase/infra/assets/9714859/d6e3b8e0-d1b7-4f69-960a-00b56cf769f3)

**Comment by Keith-CY** [comment]
> The access domain name of the grafana page embedded in the status monitoring website is: `https://grafana.magickbase.com`

Updated



![Image](https://github.com/Magickbase/infra/assets/7271329/d9907904-d69f-4dca-8220-3665e91e9fe5)
