### ISSUE TITLE
Upgrade ckb testnet node to v0.108.0-rc1

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#8]
CKB@v0.108.0-rc1: https://github.com/nervosnetwork/ckb/releases/tag/v0.108.0-rc1

All testnet nodes, except the one used for godwoken, should be upgraded.

**Comment by mdzh521** [comment]
ok i'm done with it now.

**Comment by Keith-CY** [comment]
The rc2 version has been released just now

Ref: https://github.com/nervosnetwork/ckb/releases/tag/v0.108.0-rc2

**Comment by mdzh521** [comment]
> The rc2 version has been released just now
> 
> Ref: https://github.com/nervosnetwork/ckb/releases/tag/v0.108.0-rc2

ok i'm done with it now.Just upgraded the testnet environment.
