### ISSUE TITLE
Bump CKB node to v0.116.1

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#86]
CKB Node@v0.116.1 has been released at https://github.com/nervosnetwork/ckb/releases/tag/v0.116.1

Following services could be upgraded

- [ ] CKB Explorer
- [ ] Godwoken Explorer
- [ ] Public Nodes
- [ ] Force Bridge

**Comment by guomaoqiu** [comment]
Done ✅
<img width="1077" alt="image" src="https://github.com/Magickbase/infra/assets/9714859/d16c67c1-248b-4718-96f3-d3321334a464">
