### ISSUE TITLE
Bump CKB node to v0.117.0

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#89]
CKB Node@v0.117.0 has been released at https://github.com/nervosnetwork/ckb/releases/tag/v0.117.0

Following services could be upgraded

- [ ] CKB Explorer
- [ ]  Godwoken Explorer
- [ ]  Public Nodes
- [ ] Force Bridge

Can I perform the upgrade now?  @Keith-CY

**Comment by Keith-CY** [comment]
Sure, 0.117.0 is compatible with previous versions

**Comment by guomaoqiu** [comment]
Done.
![image](https://github.com/user-attachments/assets/23dd6f82-d465-4a81-94a9-9e42375092cf)
