### ISSUE TITLE
Add a faucet for the preview chain

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#92]
The core team has deployed a preview chain for testing specific features, the chain info can be found at https://github.com/nervosnetwork/ckb/pull/4635

To facilitate developers working on the preview chain, we are expected to provide a faucet for it.

Followings are the services to have:
1. A preview chain node;
2. A backend for the faucet;
3. A page for the faucet;
4. Add link to the preview chain faucet on the active faucet page.

**Comment by Keith-CY** [comment]
The preview environment can be freed now because all features have been activated on the testnet.

**Comment by guomaoqiu** [comment]
> The preview environment can be freed now because all features have been activated on the testnet.

Done.
