### ISSUE TITLE
Bump ckb nodes to v0.118.0

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#93]
CKB Node@v0.118.0 has been released at https://github.com/nervosnetwork/ckb/releases/tag/v0.118.0

Following services could be upgraded

- [ ] CKB Explorer
- [ ] Godwoken Explorer
- [ ] Public Nodes
- [ ] Force Bridge

**Comment by guomaoqiu** [comment]
Done.
![image](https://github.com/user-attachments/assets/23f149f3-7051-4652-a7c7-cddff7b2d271)
