### ISSUE TITLE
Bump CKB Nodes to v0.120.0

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/infra#94]
CKB Node@v0.120.0 has been released at https://github.com/nervosnetwork/ckb/releases/tag/v0.120.0

Following services could be upgraded

- [ ] CKB Explorer
- [ ] Godwoken Explorer
- [ ] Public Nodes

**Comment by guomaoqiu** [comment]
Done.
![image](https://github.com/user-attachments/assets/c8fcc301-6648-46ee-bdaa-38b039d80edb)
